#!/bin/bash

# https://www.vultr.com/docs/how-to-install-jenkins-on-centos-7

sudo yum install java -y
sudo yum install wget -y
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum install jenkins -y

# sudo service jenkins start
# sudo service jenkins stop

